# Generated by Django 6.0.3 on 2026-03-18 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_rows", models.IntegerField()),
                ("seats_per_row", models.IntegerField()),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row", models.CharField(max_length=5)),
                ("number", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room_app.room"
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat",
                "verbose_name_plural": "Seats",
                "db_table": "seat",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "row", "number"), name="unique_seat_per_room"
                    )
                ],
                "unique_together": {("room", "row", "number")},
            },
        ),
    ]
