# Generated by Django 6.0.3 on 2026-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("session_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
    ]
