# Generated by Django 6.0.3 on 2026-03-18 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_movie_is_available"),
        ("room_app", "0001_initial"),
        ("session_app", "0002_session_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="movie_app.movie",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="room_app.room",
            ),
        ),
    ]
